abbr -a -U -- brc 'rails c'
abbr -a -U -- brcs 'rails c --sandbox'
abbr -a -U -- brs 'rails s -b localhost'
abbr -a -U -- dbm 'rails db:migrate'
abbr -a -U -- tka 'gitk --all &;disown'
abbr -a -U -- ytd 'caffeinate -i youtube-dl -f "bestvideo[height<=1080]+bestaudio/best[height<=1080]"'
abbr -a -U -- ytdf 'youtube-dl -F'
abbr -a -U -- ytdm 'caffeinate -i youtube-dl -f "bestvideo[height<=1440]+bestaudio/best[height<=1440]"'
abbr -a -U -- ytds 'caffeinate -i youtube-dl -f "bestvideo[height<=720]+bestaudio/best[height<=720]"'
