abbr -a -U -- brc 'rails c -- --legacy'
abbr -a -U -- brcs 'rails c -s -- --legacy'
abbr -a -U -- brs 'rails s -b localhost'
abbr -a -U -- dbm 'rails db:migrate'
abbr -a -U -- gci 'git commit'
abbr -a -U -- gcin 'git commit --no-edit'
abbr -a -U -- gco 'git checkout'
abbr -a -U -- gfco 'git fetch origin; and git checkout'
abbr -a -U -- ggb 'lazycli -- git branch'
abbr -a -U -- gpuo 'git push -u origin (git branch --show-current)'
abbr -a -U -- gsm 'git switch main'
abbr -a -U -- gss 'git switch -'
abbr -a -U -- rff 'spring rspec --format=documentation --fail-fast'
abbr -a -U -- rss 'spring rspec --format=documentation'
abbr -a -U -- tka 'gitk --all &;disown'
abbr -a -U -- ytd 'caffeinate yt-dlp -f "bestvideo[height<=1080]+bestaudio/best[height<=1080]"'
abbr -a -U -- ytdf 'yt-dlp -F'
abbr -a -U -- ytdm 'caffeinate yt-dlp -f "bestvideo[height<=1440]+bestaudio/best[height<=1440]"'
abbr -a -U -- ytds 'caffeinate yt-dlp -f "bestvideo[height<=720]+bestaudio/best[height<=720]"'
abbr -a -U -- ytda 'caffeinate yt-dlp -f "bestvideo[height<=1080]+bestaudio/best[height<=1080]" -a ~/a;and exit'
abbr -a -U -- ytdma 'caffeinate yt-dlp -f "bestvideo[height<=1440]+bestaudio/best[height<=1440]" -a ~/a;and exit'
